/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 C:\Users\48607\threeJs\projekt\public\1.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('../public/1.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane.geometry} material={nodes.Plane.material} position={[0.002, 0.022, -0.033]} />
      <mesh geometry={nodes.Plane001.geometry} material={nodes.Plane001.material} position={[0.002, 0.022, -0.033]} />
      <mesh geometry={nodes.Plane002.geometry} material={nodes.Plane002.material} position={[0.002, 0.022, -0.033]} />
      <mesh geometry={nodes.Plane004.geometry} material={nodes.Plane004.material} position={[-0.773, 1.064, -0.615]} scale={[2.966, 1, 2.392]} />
      <mesh geometry={nodes.Plane005.geometry} material={nodes.Plane005.material} position={[-0.773, 1.064, -0.615]} scale={[2.966, 1, 2.392]} />
      <mesh geometry={nodes.Plane006.geometry} material={nodes.Plane006.material} position={[-0.773, 1.064, -0.615]} scale={[2.966, 1, 2.392]} />
      <mesh geometry={nodes.Plane007.geometry} material={nodes.Plane007.material} position={[-0.773, 1.064, -0.615]} scale={[2.966, 1, 2.392]} />
      <mesh geometry={nodes.Plane008.geometry} material={nodes.Plane008.material} position={[-0.773, 1.064, -0.615]} scale={[2.966, 1, 2.392]} />
      <mesh geometry={nodes.Plane009.geometry} material={nodes.Plane009.material} position={[0.002, 0.022, -0.033]} scale={0.96} />
      <mesh geometry={nodes.Plane003.geometry} material={nodes.Plane003.material} position={[-0.808, 0.825, -0.237]} rotation={[0.004, -0.372, 0.021]} scale={[2.966, 1, 2.392]} />
      <mesh geometry={nodes.Plane010.geometry} material={nodes.Plane010.material} position={[-0.671, 0.936, -0.22]} rotation={[0, -0.374, 0]} scale={[2.966, 1, 2.392]} />
    </group>
  )
}

useGLTF.preload('../public/1.gltf')
