/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 C:\Users\48607\threeJs\projekt\public\2.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/2.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane012.geometry} material={materials.Material} scale={17.171} />
      <mesh geometry={nodes.Plane.geometry} material={materials['Material.001']} position={[0.002, 0.022, -0.033]} />
      <mesh geometry={nodes.Plane001.geometry} material={materials['Material.003']} position={[0.002, 0.022, -0.033]} />
      <mesh geometry={nodes.Plane002.geometry} material={materials['Material.002']} position={[0.002, 0.022, -0.033]} />
      <group position={[-0.773, 1.064, -0.615]} scale={[2.536, 0.855, 2.045]}>
        <mesh geometry={nodes.Plane005.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Plane005_1.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Plane005_2.geometry} material={materials['Material.014']} />
        <mesh geometry={nodes.Plane003.geometry} material={materials['Material.012']} position={[-0.012, -0.239, 0.158]} rotation={[0.01, -0.377, 0.034]} scale={[1.036, 1, 0.977]} />
        <mesh geometry={nodes.Plane005_3.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Plane006.geometry} material={nodes.Plane006.material} />
        <mesh geometry={nodes.Plane007.geometry} material={nodes.Plane007.material} />
        <mesh geometry={nodes.Plane008.geometry} material={materials['Material.008']} />
        <mesh geometry={nodes.Plane010.geometry} material={nodes.Plane010.material} position={[0.035, -0.128, 0.165]} rotation={[0, -0.379, 0]} scale={[1.035, 1, 0.976]} />
        <mesh geometry={nodes.Plane011_1.geometry} material={materials['Material.002']} position={[-0.548, 3.945, 0.994]} rotation={[Math.PI / 2, 0, 0]} scale={[0.129, 0.16, 0.383]} />
        <mesh geometry={nodes.Plane013.geometry} material={materials['Material.002']} position={[-0.263, 3.945, 0.994]} rotation={[Math.PI / 2, 0, 0]} scale={[0.129, 0.16, 0.383]} />
        <mesh geometry={nodes.Plane014.geometry} material={materials['Material.002']} position={[0.023, 3.945, 0.994]} rotation={[Math.PI / 2, 0, 0]} scale={[0.129, 0.16, 0.383]} />
        <mesh geometry={nodes.Plane015.geometry} material={materials['Material.002']} position={[0.308, 3.945, 0.994]} rotation={[Math.PI / 2, 0, 0]} scale={[0.129, 0.16, 0.383]} />
        <mesh geometry={nodes.Plane016.geometry} material={materials['Material.002']} position={[0.593, 3.945, 0.994]} rotation={[Math.PI / 2, 0, 0]} scale={[0.129, 0.16, 0.383]} />
        <mesh geometry={nodes.Plane017.geometry} material={materials['Material.002']} position={[0.879, 3.945, 0.994]} rotation={[Math.PI / 2, 0, 0]} scale={[0.129, 0.16, 0.383]} />
        <mesh geometry={nodes.Text.geometry} material={materials['Material.011']} position={[-0.63, 3.726, 1.026]} rotation={[Math.PI / 2, 0, 0]} scale={[0.337, 0.418, 1]} />
        <mesh geometry={nodes.Text001.geometry} material={materials['Material.011']} position={[-0.345, 3.726, 1.026]} rotation={[Math.PI / 2, 0, 0]} scale={[0.337, 0.418, 1]} />
        <mesh geometry={nodes.Text002.geometry} material={materials['Material.011']} position={[-0.025, 3.674, 1.026]} rotation={[Math.PI / 2, 0, 0]} scale={[0.256, 0.318, 0.76]} />
        <mesh geometry={nodes.Text003.geometry} material={materials['Material.011']} position={[0.267, 3.688, 1.026]} rotation={[Math.PI / 2, 0, 0]} scale={[0.237, 0.294, 0.704]} />
        <mesh geometry={nodes.Text004.geometry} material={materials['Material.011']} position={[0.512, 3.726, 1.026]} rotation={[Math.PI / 2, 0, 0]} scale={[0.337, 0.418, 1]} />
        <mesh geometry={nodes.Text005.geometry} material={materials['Material.011']} position={[0.797, 3.726, 1.026]} rotation={[Math.PI / 2, 0, 0]} scale={[0.337, 0.418, 1]} />
      </group>
      <mesh geometry={nodes.Plane009.geometry} material={materials['Material.013']} position={[0.002, 0.022, -0.033]} scale={0.96} />
      <group position={[-3.425, 0.94, 3.028]} scale={0.339}>
        <mesh geometry={nodes.Circle001.geometry} material={materials['Material.013']} />
        <mesh geometry={nodes.Circle001_1.geometry} material={materials['Material.007']} />
      </group>
      <mesh geometry={nodes.Plane019.geometry} material={materials['Material.002']} position={[-0.773, 1.064, -0.615]} scale={[2.536, 0.855, 2.045]} />
    </group>
  )
}

useGLTF.preload('/2.glb')
